### ISSUE TITLE
Forge Items

### ISSUE THREAD

**Issue by KhaozFrost** [mmonkey/Automator#1]
I'm wanting to map pixelmon tools to this plugin but it doesn't seem to work.
ie. http://pixelmonmod.com/wiki/index.php?title=Evolution_stone_tools

**Comment by mmonkey** [comment]
I will investigate this when I have a chance. Within the next couple of weeks for sure.

**Comment by mmonkey** [comment]
Hey thanks for your patience! I did some testing, and pixelmon tools work with the latest version of Automator. I will update the readme shortly with examples.
